# Generated by Django 4.2 on 2023-04-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=128)),
                ('hardware', models.CharField(max_length=256)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateField()),
                ('status', models.SmallIntegerField()),
                ('active', models.BooleanField(default=1)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
